name: Test OIDC Connection

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

env:
  AWS_REGION: ap-southeast-2

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::314146297130:role/OIDCRole_iamadmin_general
          aws-region: ${{ env.AWS_REGION }}

      - name: Test AWS connection
        run: |
          echo "Testing AWS OIDC connection..."
          aws sts get-caller-identity
          
          echo "Testing Lambda permissions..."
          aws lambda list-functions --max-items 5
          
          echo "Testing API Gateway permissions..."
          aws apigateway get-rest-apis --max-items 5
          
          echo "✅ OIDC connection successful!"

      - name: Check Lambda function
        run: |
          if aws lambda get-function --function-name resume-analyzer 2>/dev/null; then
            echo "✅ Lambda function 'resume-analyzer' exists"
            aws lambda get-function --function-name resume-analyzer --query 'Configuration.{FunctionName:FunctionName,Runtime:Runtime,State:State}'
          else
            echo "ℹ️  Lambda function 'resume-analyzer' does not exist yet"
          fi

      - name: Check API Gateway
        run: |
          API_ID=$(aws apigateway get-rest-apis --query "items[?name=='resume-analyzer-api'].id" --output text)
          if [ -n "$API_ID" ] && [ "$API_ID" != "None" ]; then
            echo "✅ API Gateway 'resume-analyzer-api' exists with ID: $API_ID"
            API_URL="https://$API_ID.execute-api.${{ env.AWS_REGION }}.amazonaws.com/prod"
            echo "API URL: $API_URL"
          else
            echo "ℹ️  API Gateway 'resume-analyzer-api' does not exist yet"
          fi
